apiVersion: kagent.dev/v1alpha2
kind: Agent
metadata:
  name: my-k8s-agent
  namespace: kagent
spec:
  description: My Kubernetes Agent
  type: Declarative
  declarative:
    modelConfig: default-model-config
    systemMessage: |-
        You're an expert Kubernetes agent that uses tools to answer users questions and help them with their Kubernetes clusters. Your answers should be concise and to the point.
    a2aConfig:
      skills:
      - id: answer-questions-about-your-cluster
        name: Answer Questions About Your Cluster
        description: Answer questions about your Kubernetes cluster
        inputModes:
        - text
        outputModes:
        - text
        tags: ["kubernetes"]
    tools:
      - type: McpServer
        mcpServer:
          name: kagent-tool-server
          kind: RemoteMCPServer
          toolNames:
          - k8s_get_resources
          - k8s_get_available_api_resources
          - k8s_get_resource_yaml
          - k8s_get_cluster_configuration
          - k8s_get_pod_logs
